### ISSUE TITLE
Did MyWBSC change something?

### ISSUE THREAD

**Issue by endorphin319** [keero/baseball-streaming#7]
Since this afternoon I get:

java -jar /Users/mpls/Downloads/game6/baseball-streaming-v1.9.3.jar -t /Users/mpls/Downloads/game6 -S https://stats.knbsbstats.nl -s 2024-lucky-day-hoofdklasse-honkbal -g 129242 -m replay

[main] INFO org.sundbybergheat.baseballstreaming.services.PlayByPlayService - Replaying game 129242 with 319 plays, updating with 3000 millisecond interval.
[main] INFO org.sundbybergheat.baseballstreaming.clients.StatsClient - Fetching stats for ROJAS Timothy (id=405436) in 'Hoofdklasse Honkbal'.
[main] ERROR org.sundbybergheat.baseballstreaming.services.FilesService - Something went wrong
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot coerce empty String ("") to `org.sundbybergheat.baseballstreaming.models.stats.CareerStatsImpl$Json` value (but could if coercion was enabled using `CoercionConfig`)
 at [Source: (String)""""; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadCoercion(DeserializationContext.java:1806)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._checkCoercionFail(StdDeserializer.java:1443)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromEmptyString(StdDeserializer.java:325)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:270)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1495)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:196)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:186)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1488)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:196)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:186)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at org.sundbybergheat.baseballstreaming.models.JsonMapper.fromJson(JsonMapper.java:22)
	at org.sundbybergheat.baseballstreaming.clients.StatsClient.getCategoryStats(StatsClient.java:533)
	at org.sundbybergheat.baseballstreaming.clients.StatsClient.getPlayerStats(StatsClient.java:87)
	at org.sundbybergheat.baseballstreaming.services.FilesService.updateBatter(FilesService.java:381)
	at org.sundbybergheat.baseballstreaming.services.FilesService.updateLineups(FilesService.java:729)
	at org.sundbybergheat.baseballstreaming.services.FilesService.updateState(FilesService.java:104)
	at org.sundbybergheat.baseballstreaming.services.FilesService.updatePlay(FilesService.java:98)
	at org.sundbybergheat.baseballstreaming.services.PlayByPlayService.run(PlayByPlayService.java:85)
	at org.sundbybergheat.baseballstreaming.App.main(App.java:144)
[main] INFO org.sundbybergheat.baseballstreaming.services.PlayByPlayService - Play # 1 (2024-06-04T17:17:34.558Z): Awaiting Play Ball
[main] INFO org.sundbybergheat.baseballstreaming.clients.StatsClient - Fetching stats for ROJAS Timothy (id=405436) in 'Hoofdklasse Honkbal'.
[main] ERROR org.sundbybergheat.baseballstreaming.services.FilesService - Something went wrong
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot coerce empty String ("") to `org.sundbybergheat.baseballstreaming.models.stats.CareerStatsImpl$Json` value (but could if coercion was enabled using `CoercionConfig`)

**Comment by molano999** [comment]
Looks to be a problem on the WBSC backend.  
When you go to this player's webpage, it does not load either: https://stats.knbsbstats.nl/en/events/2024-lucky-day-hoofdklasse-honkbal/teams/28601/players/405436

I checked on a random game and player from our Belgian league and it also does not load:
https://www.baseballsoftball.be/en/events/2024-baseball-d1/teams/29253/players/391204
or
https://www.baseballsoftball.be/en/events/2024-baseball-d1/teams/28946/players/412048

I do not think there is an option here right now to not take in any stats, so I do not see a quick solution for this.

**Comment by molano999** [comment]
Seems to be a certificate error.  Probably not valid anymore and needs to be renewed.  Checking further:
js?id=G-BGRD71QFF3:204 
        
        
` POST https://region1.google-analytics.com/g/collect?v=2&tid=G-BGRD71QFF3&gtm=45je4650v9111129681za200&_p=1717793554832&gcd=13l3l3l2l1&npa=1&dma_cps=sypham&dma=1&tag_exp=0&cid=390025315.1681312566&ul=en-us&sr=1920x1080&uaa=x86&uab=64&uafvl=Google%2520Chrome%3B125.0.6422.77%7CChromium%3B125.0.6422.77%7CNot.A%252FBrand%3B24.0.0.0&uamb=0&uam=&uap=Windows&uapv=10.0.0&uaw=0&are=1&frm=0&pscdl=noapi&_s=1&sid=1717793179&sct=419&seg=1&dl=https%3A%2F%2Fwww.baseballsoftball.be%2Fen%2Fevents%2F2024-baseball-d1%2Fteams%2F28946%2Fplayers%2F412048&dt=Koninklijke%20Belgische%20Base%20en%20Softball%20Federatie%20-%20F%C3%A9d%C3%A9ration%20Royale%20Belge%20de%20Base%20et%20Softball%20-%20Baseball%20D1%202024&en=page_view&_ee=1&tfd=8334 net::
ERR_CERT_COMMON_NAME_INVALID`

**Comment by molano999** [comment]
Same thing happens when you go to the full career (which is really really on the WBSC domain):

https://www.wbsc.org/en/player/rojas-timothy-782904/history
https://www.wbsc.org/en/player/ballardini-lino-587796/history

**Comment by molano999** [comment]
API calls are also simply empty.
https://www.wbsc.org/api/v1/player/stats?tab=career&fedId=278&eventCategory=EU-BASEBALL-FEDERATION-CUP-M-BB&pId=587796

**Comment by endorphin319** [comment]
Ok Thanks for checking! Will probably be resolved soon.

**Comment by molano999** [comment]
Solved
